(function(){
  const STORE_ITEMS=[{icon:'🪙',title:'Starter Coins',desc:'Enough to test small custom puzzles and hints.',coins:5000,price:'₹99 / $0.99 prototype'},{icon:'🎨',title:'Creator Pack',desc:'Coins for 20–50 piece custom puzzle publishing.',coins:40000,price:'₹499 / $4.99 prototype'},{icon:'🏆',title:'Master Puzzle Pack',desc:'Large coin pack for advanced 100+ piece creations.',coins:150000,price:'₹1,499 / $14.99 prototype'},{icon:'💡',title:'Hint Bundle',desc:'Production build can sell extra hint bundles.',coins:2500,price:'Bonus: 2,500 coins'},{icon:'🧢',title:'Avatar Cosmetics',desc:'Frames, badges, seasonal emojis, and profile effects.',coins:10000,price:'Coming soon'},{icon:'🎉',title:'Season Event Pass',desc:'Festival tournaments with leaderboard rewards.',coins:20000,price:'Coming soon'}];
  function $(id){return document.getElementById(id)}
  function getState(){try{return state}catch(e){return null}}
  function saveState(){try{save()}catch(e){}}
  function updateAvatarVisuals(){const s=getState();if(!s)return;const html=s.player.avatarImage?`<img src="${s.player.avatarImage}" alt="Avatar">`:(s.player.avatar||'🧩');if($('avatarBtn'))$('avatarBtn').innerHTML=html;if($('profileAvatarBig'))$('profileAvatarBig').innerHTML=html;if($('authLabel'))$('authLabel').textContent=s.auth?.email?'Email':'Guest';if($('profileEmail'))$('profileEmail').textContent=s.auth?.email||'Guest mode'}
  function renderStore(){const list=$('storeList');if(!list)return;list.innerHTML='';STORE_ITEMS.forEach(item=>{const card=document.createElement('article');card.className='store-card';card.innerHTML=`<div class="store-icon">${item.icon}</div><h3>${item.title}</h3><p>${item.desc}</p><div class="store-price">${item.price}</div><button class="primary-btn">Prototype Buy</button>`;card.querySelector('button').onclick=()=>{const s=getState();if(s){s.player.coins+=item.coins;saveState();try{renderChrome()}catch(e){}updateAvatarVisuals()}alert(`${item.title}: added ${item.coins.toLocaleString('en-IN')} coins in prototype mode.`)};list.appendChild(card)})}
  function showLogin(){if(localStorage.getItem('puzzleverse.login.seen'))return;const wrap=document.createElement('section');wrap.id='loginOverlay';wrap.className='login-screen active';wrap.innerHTML=`<div class="login-card"><img src="assets/branding/puzzleverse-logo.svg" alt="PuzzleVerse" class="login-logo"><span class="eyebrow">PuzzleVerse Account</span><h1>Build. Solve. Challenge the world.</h1><p class="small-muted">Use guest mode for testing, or sign in locally with email. Production should connect this to Firebase/Supabase or your own secure server.</p><form id="pvLoginForm" class="login-form"><label>Email<input id="pvLoginEmail" type="email" placeholder="you@example.com"></label><label>Display name<input id="pvLoginName" type="text" placeholder="Guest Creator"></label><button class="primary-btn" type="submit">Login / Create Account</button></form><button id="pvGuestBtn" class="ghost-btn wide">Continue as Guest</button></div>`;document.body.appendChild(wrap);$('pvGuestBtn').onclick=()=>{localStorage.setItem('puzzleverse.login.seen','1');wrap.remove()};$('pvLoginForm').onsubmit=e=>{e.preventDefault();const s=getState();if(s){s.auth=s.auth||{};s.auth.email=$('pvLoginEmail').value.trim();s.auth.mode='email';s.auth.loggedIn=true;const name=$('pvLoginName').value.trim();if(name)s.player.name=name;saveState();try{renderChrome()}catch(e){}updateAvatarVisuals()}localStorage.setItem('puzzleverse.login.seen','1');wrap.remove()}}
  function enhanceAvatarDialog(){const dlg=$('avatarDialog');if(!dlg)return;const saveBtn=$('saveAvatar'),removeBtn=$('removeAvatarImage');if(saveBtn)saveBtn.onclick=()=>{const s=getState();if(!s)return;s.player.name=$('nameInput').value.trim()||'Guest Creator';s.player.avatar=$('avatarInput').value;const file=$('avatarImageInput')?.files?.[0];if(file&&file.type.startsWith('image/')){const reader=new FileReader();reader.onload=()=>{s.player.avatarImage=reader.result;saveState();try{renderChrome()}catch(e){}updateAvatarVisuals();dlg.close()};reader.readAsDataURL(file)}else{saveState();try{renderChrome()}catch(e){}updateAvatarVisuals();dlg.close()}};if(removeBtn)removeBtn.onclick=()=>{const s=getState();if(!s)return;s.player.avatarImage='';saveState();try{renderChrome()}catch(e){}updateAvatarVisuals()};if($('openAvatarEditor'))$('openAvatarEditor').onclick=()=>$('avatarBtn').click()}
  const oldSet=window.setScreen||((typeof setScreen==='function')?setScreen:null);if(oldSet){window.setScreen=function(id){oldSet(id);if(id==='storeScreen')renderStore();if(id==='profileScreen')updateAvatarVisuals()}}
  setTimeout(()=>{renderStore();enhanceAvatarDialog();updateAvatarVisuals();showLogin()},150)
})();